n1 = float(input('Digite um numero: '))
n2 = float(input('Digite outro numero '))
soma = round((n1 + n2), 1)
print('A soma do {} e {} é {}'.format(n1, n2, soma))
print('n1 é ', type(n1), 'n2 é ', type(n2), 'soma é', type(soma))
