algo = input('Digite algo: ')
print('O tipo primitivo é: ', type(algo))
print('So tem espaços: ', algo.isspace())
print('É um numero: ', algo.isnumeric())
print('É alfanumerico: ', algo.isalnum())
print('É alfabetico: ', algo.isalpha())
print('Está em Maiuscula: ', algo.isupper())
print('Está em minuscula: ', algo.islower())
print('Está copitalizada: ', algo.istitle())
